/** Finite owner inventory. This index is not evidence that its browser owners passed. */
export const PRESENTATION_VIEW_FAMILIES = {
  catalog: {
    requirement: "ui.model-property-priority-catalog-views",
    file: "tests/e2e/src/app/shared-policy/property-priority-catalog.test.ts",
    views: [
      "course/course-detail/web",
      "course/course-detail/web-history",
      "course/course-list/web",
      "section/section-detail/web",
      "section/section-list/web",
      "teacher/teacher-detail/web",
      "teacher/teacher-detail/web-history",
      "teacher/teacher-list/web",
    ],
  },
  workspace: {
    requirement: "ui.model-property-priority-workspace-views",
    file: "tests/e2e/src/app/shared-policy/property-priority-workspace.test.ts",
    views: [
      "calendar/event-card/web",
      "calendar/personal-calendar-view/web",
      "calendar/section-calendar-view/web",
      "exam/cross-section-exam-list/web",
      "exam/section-exam-info/web",
      "homework/cross-section-homework-summary/web-detail",
      "homework/cross-section-homework-summary/web-list",
      "homework/homework-completion/web",
      "homework/section-homework-tab/web",
      "ical/personal-calendar-subscription/web",
      "ical/section-calendar-dialog/web",
      "overview/authenticated-overview/web",
      "overview/workspace-shell-navigation/web",
      "schedule/my-schedule/web",
      "schedule/section-schedule/web",
      "section/section-ical/web",
      "subscribed-sections/subscribed-sections-tab/web",
      "subscription/batch-subscribe-by-codes/web-import",
      "subscription/batch-subscribe-by-codes/web-quick-add",
      "subscription/update-kind/web",
      "todo/todo-edit/web",
      "todo/todo-list/web-detail",
      "todo/todo-list/web-list",
    ],
  },
  account: {
    requirement: "ui.model-property-priority-account-views",
    file: "tests/e2e/src/app/shared-policy/property-priority-account.test.ts",
    views: [
      "oauth/authorization-management/web",
      "oauth/authorization/web",
      "oauth/client-registration/web",
      "oauth/device-authorization-grant/web-approval",
      "oauth/device-authorization-grant/web-code",
      "oauth/device-authorization-grant/web-result",
      "user/first-login-welcome/web-orientation",
      "user/first-login-welcome/web-profile",
      "user/first-login-welcome/web-subscriptions",
      "user/settings/web-accounts",
      "user/settings/web-authorizations",
      "user/settings/web-profile",
      "user/settings/web-security",
    ],
  },
  admin: {
    requirement: "ui.model-property-priority-admin-views",
    file: "tests/e2e/src/app/shared-policy/property-priority-admin.test.ts",
    views: [
      "admin/bus-management/web",
      "admin/moderation/web-comments",
      "admin/moderation/web-descriptions",
      "admin/oauth-client-management/web",
      "admin/user-management/web",
      "comment/comment-governance/web",
      "description/description-governance/web",
      "homework/homework-governance/web",
    ],
  },
  community: {
    requirement: "ui.model-property-priority-community-views",
    file: "tests/e2e/src/app/shared-policy/property-priority-community.test.ts",
    views: [
      "comment/object-comment-section/web",
      "description/object-description-section/web",
      "upload/comment-attachment-download/web",
      "upload/comment-attachment-upload/web",
      "upload/upload-list/web",
      "upload/upload-manage/web",
      "user/public-profile/web",
    ],
  },
  discovery: {
    requirement: "ui.model-property-priority-discovery-views",
    file: "tests/e2e/src/app/shared-policy/property-priority-discovery.test.ts",
    views: [
      "bus/bus-map/web",
      "bus/bus-next-departures/web",
      "bus/bus-route-search/web",
      "bus/bus-timetable/web",
      "catalog-link/link-browse/web",
      "catalog-link/link-pin-and-visit/web",
      "overview/anonymous-overview/web",
      "publications/publication-read/web-detail",
      "publications/publication-read/web-list",
      "publications/publication-source-directory/web",
      "weather/weather/web",
      "young-event/young-event/web-calendar",
      "young-event/young-event/web-detail",
      "young-event/young-event/web-list",
      "young-event/young-event/web-organizers",
    ],
  },
} as const;
export type PresentationViewFamily = keyof typeof PRESENTATION_VIEW_FAMILIES;
