/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7ff9995e0bb66b383179c4791463e05b)
interface __BaseEnv_Env {
	CALENDAR_EXPORTS: KVNamespace;
	CATALOG_DETAIL_CORE: KVNamespace;
	WEATHER: KVNamespace;
	R2_UPLOADS: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	HYPERDRIVE_AUTH: Hyperdrive;
	HYPERDRIVE_MAINTENANCE: Hyperdrive;
	ANALYTICS: AnalyticsEngineDataset;
	CALENDAR_EXPORT_REBUILD: Queue;
	AUDIT_LOG_WRITES: Queue;
	USER_WRITE_RATE_LIMITER: RateLimit;
	USER_BATCH_WRITE_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	NODE_ENV: "production";
	APP_PUBLIC_ORIGIN: "https://life-ustc.tiankaima.dev";
	DATABASE_URL: string;
	ALLOW_DATABASE_SEED: string;
	WEBHOOK_SECRET: string;
	AUTH_SECRET: string;
	AUTH_OIDC_ISSUER: string;
	AUTH_OIDC_CLIENT_ID: string;
	AUTH_OIDC_CLIENT_SECRET: string;
	UPLOAD_TOTAL_QUOTA_MB: string;
	DEV_DEBUG_USERNAME: string;
	DEV_DEBUG_NAME: string;
	DEV_ADMIN_USERNAME: string;
	DEV_ADMIN_NAME: string;
	DEV_DEBUG_PASSWORD: string;
	DEV_ADMIN_PASSWORD: string;
	AMAP_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "APP_PUBLIC_ORIGIN" | "DATABASE_URL" | "ALLOW_DATABASE_SEED" | "WEBHOOK_SECRET" | "AUTH_SECRET" | "AUTH_OIDC_ISSUER" | "AUTH_OIDC_CLIENT_ID" | "AUTH_OIDC_CLIENT_SECRET" | "UPLOAD_TOTAL_QUOTA_MB" | "DEV_DEBUG_USERNAME" | "DEV_DEBUG_NAME" | "DEV_ADMIN_USERNAME" | "DEV_ADMIN_NAME" | "DEV_DEBUG_PASSWORD" | "DEV_ADMIN_PASSWORD" | "AMAP_API_KEY">> {}
}
