/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 499d1524763c8a18a87d6c6dad2d6f67)
interface __BaseEnv_Env {
	CALENDAR_EXPORTS: KVNamespace;
	CATALOG_DETAIL_CORE: KVNamespace;
	WEATHER: KVNamespace;
	R2_UPLOADS: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	HYPERDRIVE_AUTH: Hyperdrive;
	HYPERDRIVE_MAINTENANCE: Hyperdrive;
	ANALYTICS: AnalyticsEngineDataset;
	CALENDAR_EXPORT_REBUILD: Queue;
	AUDIT_LOG_WRITES: Queue;
	USER_WRITE_RATE_LIMITER: RateLimit;
	USER_BATCH_WRITE_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	NODE_ENV: "production";
	APP_PUBLIC_ORIGIN: "https://life-ustc.tiankaima.dev";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "APP_PUBLIC_ORIGIN">> {}
}
