/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false` (hash: 3a7f42782d2c249ab96113b0f41e7b21)
interface __BaseEnv_Env {
	CALENDAR_EXPORTS: KVNamespace;
	CATALOG_DETAIL_CORE: KVNamespace;
	R2_UPLOADS: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	HYPERDRIVE_AUTH: Hyperdrive;
	ANALYTICS: AnalyticsEngineDataset;
	CALENDAR_EXPORT_REBUILD: Queue;
	USER_WRITE_RATE_LIMITER: RateLimit;
	USER_BATCH_WRITE_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	NODE_ENV: "production";
	APP_PUBLIC_ORIGIN: "https://life-ustc.tiankaima.dev";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "APP_PUBLIC_ORIGIN">> {}
}
