// Shared spelling for native test tags. Only collected combinations create jobs.
export const testTags = [
  "Account",
  "Admin",
  "Bus",
  "Calendar",
  "CatalogLink",
  "CatalogMetadata",
  "Comment",
  "Course",
  "Database",
  "Description",
  "Exam",
  "GraphQL",
  "Homework",
  "Infrastructure",
  "MCP",
  "OAuth",
  "OpenAPI",
  "Overview",
  "Publication",
  "RoomMap",
  "Schedule",
  "Search",
  "Section",
  "Semester",
  "Site",
  "StaticImport",
  "Subscription",
  "Teacher",
  "Todo",
  "Upload",
  "User",
  "Weather",
  "Young",
].flatMap((domain) =>
  [
    "Service",
    "REST",
    "GraphQL",
    "MCP",
    "ICS",
    "Web",
    "OAuth",
    "Runtime",
    "Permissions",
  ].map((method) => ({ name: `@${domain}/${method}` })),
);
