import { isProductionEnvironment } from "@/lib/log/app-logger-core";

/**
 * Deterministic request sampling keeps all log points for a request aligned.
 * The request ID is generated by the Worker or application, never accepted
 * from an untrusted request header.
 */
export function shouldLogSampledSuccess(
  requestId: string,
  samplePercent: number,
) {
  if (!isProductionEnvironment()) return true;
  if (!Number.isFinite(samplePercent) || samplePercent <= 0) return false;
  if (samplePercent >= 100) return true;

  let hash = 0;
  for (let index = 0; index < requestId.length; index += 1) {
    hash = (hash * 31 + requestId.charCodeAt(index)) >>> 0;
  }
  return hash % 100 < samplePercent;
}

export function shouldLogSuccessfulRequest(input: {
  durationMs: number;
  requestId: string;
  samplePercent: number;
  status: number;
}) {
  return (
    input.status >= 400 ||
    input.durationMs >= 1_000 ||
    shouldLogSampledSuccess(input.requestId, input.samplePercent)
  );
}
