-- The publication crawler is a server-managed OAuth client.  It cannot be
-- created through public dynamic registration because its scope is an
-- administrator-only REST capability.  Keep this id reserved and make the
-- migration idempotent so every deployment has one usable device client.
INSERT INTO "OAuthClient" (
  "id",
  "clientId",
  "clientSecret",
  "clientDiscoveryId",
  "disabled",
  "skipConsent",
  "enableEndSession",
  "subjectType",
  "scopes",
  "clientCredentialsScopes",
  "name",
  "contacts",
  "redirectUris",
  "postLogoutRedirectUris",
  "tokenEndpointAuthMethod",
  "applicationType",
  "grantTypes",
  "responseTypes",
  "public",
  "type",
  "requirePKCE",
  "dpopBoundAccessTokens",
  "referenceId",
  "metadata",
  "createdAt",
  "updatedAt"
)
VALUES (
  'life-ustc-publication-crawler',
  'life-ustc-publication-crawler',
  NULL,
  NULL,
  false,
  false,
  false,
  NULL,
  ARRAY['publication.ingest:write', 'offline_access']::TEXT[],
  ARRAY[]::TEXT[],
  'Life@USTC publication crawler',
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'none',
  'native',
  ARRAY['urn:ietf:params:oauth:grant-type:device_code', 'refresh_token']::TEXT[],
  ARRAY[]::TEXT[],
  true,
  'public',
  false,
  false,
  NULL,
  '{"source":"system_publication_crawler","provisionedBy":"migration"}'::JSONB,
  NOW(),
  NOW()
)
ON CONFLICT ("clientId") DO UPDATE SET
  "clientSecret" = NULL,
  "clientDiscoveryId" = NULL,
  "disabled" = false,
  "skipConsent" = false,
  "enableEndSession" = false,
  "subjectType" = NULL,
  "scopes" = EXCLUDED."scopes",
  "clientCredentialsScopes" = EXCLUDED."clientCredentialsScopes",
  "name" = EXCLUDED."name",
  "contacts" = EXCLUDED."contacts",
  "redirectUris" = EXCLUDED."redirectUris",
  "postLogoutRedirectUris" = EXCLUDED."postLogoutRedirectUris",
  "tokenEndpointAuthMethod" = EXCLUDED."tokenEndpointAuthMethod",
  "applicationType" = EXCLUDED."applicationType",
  "grantTypes" = EXCLUDED."grantTypes",
  "responseTypes" = EXCLUDED."responseTypes",
  "public" = EXCLUDED."public",
  "type" = EXCLUDED."type",
  "requirePKCE" = EXCLUDED."requirePKCE",
  "dpopBoundAccessTokens" = EXCLUDED."dpopBoundAccessTokens",
  "userId" = NULL,
  "referenceId" = NULL,
  "metadata" = EXCLUDED."metadata",
  "updatedAt" = NOW();
