ALTER TABLE "Schedule"
ALTER COLUMN "periods" TYPE DOUBLE PRECISION
USING "periods"::DOUBLE PRECISION;

ALTER TABLE "ScheduleGroup"
ALTER COLUMN "actualPeriods" TYPE DOUBLE PRECISION
USING "actualPeriods"::DOUBLE PRECISION;

ALTER TABLE "Section"
ALTER COLUMN "periodsPerWeek" TYPE DOUBLE PRECISION
USING "periodsPerWeek"::DOUBLE PRECISION,
ALTER COLUMN "actualPeriods" TYPE DOUBLE PRECISION
USING "actualPeriods"::DOUBLE PRECISION;

ALTER TABLE "TeacherAssignment"
ALTER COLUMN "period" TYPE DOUBLE PRECISION
USING "period"::DOUBLE PRECISION;
